MatchingEngine:
  matchingEngine:
    db:
      hBlobConnString: DefaultEndpointsProtocol=https;AccountName=sbwltmetest;AccountKey=8UY02TesqkWQKqucDk64LbvS19hBswYFTouFDlkr1t3EGubMt+TlPk5/ng3kfDDQSczmHppAgEydPo6WOyuI+A==;EndpointSuffix=core.windows.net
      hBestPriceConnString: DefaultEndpointsProtocol=https;AccountName=sbwltmetest;AccountKey=8UY02TesqkWQKqucDk64LbvS19hBswYFTouFDlkr1t3EGubMt+TlPk5/ng3kfDDQSczmHppAgEydPo6WOyuI+A==;EndpointSuffix=core.windows.net
      hCandlesConnString: DefaultEndpointsProtocol=https;AccountName=sbwltmetest;AccountKey=8UY02TesqkWQKqucDk64LbvS19hBswYFTouFDlkr1t3EGubMt+TlPk5/ng3kfDDQSczmHppAgEydPo6WOyuI+A==;EndpointSuffix=core.windows.net
      hHourCandlesConnString: DefaultEndpointsProtocol=https;AccountName=sbwltmetest;AccountKey=8UY02TesqkWQKqucDk64LbvS19hBswYFTouFDlkr1t3EGubMt+TlPk5/ng3kfDDQSczmHppAgEydPo6WOyuI+A==;EndpointSuffix=core.windows.net
      balancesInfoConnString: DefaultEndpointsProtocol=https;AccountName=sbwltmetest;AccountKey=8UY02TesqkWQKqucDk64LbvS19hBswYFTouFDlkr1t3EGubMt+TlPk5/ng3kfDDQSczmHppAgEydPo6WOyuI+A==;EndpointSuffix=core.windows.net
      hTradesConnString: DefaultEndpointsProtocol=https;AccountName=sbwltmetest;AccountKey=8UY02TesqkWQKqucDk64LbvS19hBswYFTouFDlkr1t3EGubMt+TlPk5/ng3kfDDQSczmHppAgEydPo6WOyuI+A==;EndpointSuffix=core.windows.net
      dictsConnString: DefaultEndpointsProtocol=https;AccountName=sbwltmetest;AccountKey=8UY02TesqkWQKqucDk64LbvS19hBswYFTouFDlkr1t3EGubMt+TlPk5/ng3kfDDQSczmHppAgEydPo6WOyuI+A==;EndpointSuffix=core.windows.net
      sharedStorageConnString: DefaultEndpointsProtocol=https;AccountName=sbwltmetest;AccountKey=8UY02TesqkWQKqucDk64LbvS19hBswYFTouFDlkr1t3EGubMt+TlPk5/ng3kfDDQSczmHppAgEydPo6WOyuI+A==;EndpointSuffix=core.windows.net
      messageLogConnString: DefaultEndpointsProtocol=https;AccountName=sbwltmetest;AccountKey=8UY02TesqkWQKqucDk64LbvS19hBswYFTouFDlkr1t3EGubMt+TlPk5/ng3kfDDQSczmHppAgEydPo6WOyuI+A==;EndpointSuffix=core.windows.net
      matchingEngineConnString: DefaultEndpointsProtocol=https;AccountName=sbwltmetest;AccountKey=8UY02TesqkWQKqucDk64LbvS19hBswYFTouFDlkr1t3EGubMt+TlPk5/ng3kfDDQSczmHppAgEydPo6WOyuI+A==;EndpointSuffix=core.windows.net
      monitoringConnString: DefaultEndpointsProtocol=https;AccountName=sbwltmetest;AccountKey=8UY02TesqkWQKqucDk64LbvS19hBswYFTouFDlkr1t3EGubMt+TlPk5/ng3kfDDQSczmHppAgEydPo6WOyuI+A==;EndpointSuffix=core.windows.net
      reservedVolumesConnString: DefaultEndpointsProtocol=https;AccountName=sbwltmetest;AccountKey=8UY02TesqkWQKqucDk64LbvS19hBswYFTouFDlkr1t3EGubMt+TlPk5/ng3kfDDQSczmHppAgEydPo6WOyuI+A==;EndpointSuffix=core.windows.net
      accountsTableName: Balances
      newAccountsTableName: Balances
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 1000
      useSsl: false
      balanceDatabase: 0
      processedMessageDatabase: 1
      processedCashMessageDatabase: 2
      ordersDatabase: 3
      pingDatabase: 4
      sequenceNumberDatabase: 5
      outgoingEventsDatabase: 6
      outgoingEventsTtl: 3600
    grpcEndpoints:
      cashApiServicePort: 5001
      tradingApiServicePort: 5002
      balancesServicePort: 5003
      orderBooksServicePort: 5004
      dictionariesConnection: assets-dictionary.spot-services.svc.cluster.local
      outgoingEventsConnections:
        - localhost:95
      outgoingTrustedClientsEventsConnections:
        - localhost:95
    socket:
      port: 8888
      maxConnections: 100
    serverOrderBookPort: 8887
    serverOrderBookMaxConnections: 10
    httpOrderBookPort: 8886
    httpApiPort: 8885
    bestPricesInterval: 100000
    candleSaverInterval: 100000
    hoursCandleSaverInterval: 100000
    correctReservedVolumes: true
    cancelMinVolumeOrders: true
    cancelAllOrders: false
    orderBookPath: store/orderbooks
    secondaryStopOrderBookPath: store/stoporderbooks-secondary
    secondaryOrderBookPath: store/orderbooks-secondary
    stopOrderBookPath: store/stoporderbooks
    queueConfig:
      queueSizeHealthCheckInterval: 10000
      queueSizeLoggerInterval: 60000
      queueSizeLimit: 1
      maxQueueSizeLimit: 1
      recoverQueueSizeLimit: 5
      outgoingMaxQueueSizeLimit: 1
      outgoingRecoverQueueSizeLimit: 5
      dataMaxQueueSizeLimit: 1
      dataRecoverQueueSizeLimit: 5
    name: Spot.MatchingEngine
    aliveStatus:
      updatePeriod: 10000
      lifeTime: 100000
    processedMessagesPath: store/processed
    processedMessagesInterval: 60000
    performanceStatsInterval: 60000
    keepAlive:
      passive: true
      port: 8880
      name: Spot.MatchingEngine
    logFilesCleaner:
      enabled: false
    storage: Redis
    walletsMigration: false
    writeBalancesToSecondaryDb: true
    ordersMigration: false
    writeOrdersToSecondaryDb: true
  slackNotifications:
    azureQueue:
      connectionString: DefaultEndpointsProtocol=https;AccountName=sbwltmetest;AccountKey=8UY02TesqkWQKqucDk64LbvS19hBswYFTouFDlkr1t3EGubMt+TlPk5/ng3kfDDQSczmHppAgEydPo6WOyuI+A==;EndpointSuffix=core.windows.net
      queueName: TestQueue
  throttlingLogger:
    limitSeconds: 5