# Ubuntu 15.04 with Java 8 installed
 
FROM adoptopenjdk:8-jdk-hotspot
RUN apt-get update && \
	apt-get install unzip && \
    apt-get clean
	
ADD MyJetWallet.MatchingEngine-1.0.zip .
RUN unzip -q MyJetWallet.MatchingEngine-1.0.zip && \
    rm MyJetWallet.MatchingEngine-1.0.zip && \
    mv MyJetWallet.MatchingEngine-* MyJetWallet.MatchingEngine && \
    chmod +x MyJetWallet.MatchingEngine/bin/start.sh && \
    chmod +x MyJetWallet.MatchingEngine/bin/stop.sh && \
    sed -i -e 's/\r$//' MyJetWallet.MatchingEngine/bin/start.sh && \
    sed -i -e 's/\r$//' MyJetWallet.MatchingEngine/bin/stop.sh

EXPOSE 8886 8887 8888 8889

ENTRYPOINT ["/MyJetWallet.MatchingEngine/bin/start.sh"]
CMD ["--console"]